version : "3.8"

services:

  front-end:
    depends_on:
      - back-end
    container_name: app
    build:
      context: ./front-end
      dockerfile: ../docker/front-end.dockerfile
    volumes:
      - ./front-end:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  back-end:
    depends_on:
      - db
    container_name: api
    build:
      context: ./back-end
      dockerfile: ../docker/back-end.dockerfile
    volumes:
      - ./back-end:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./docker/.env/.env_db

  db:
    container_name: database
    build:
      context: ./docker
      dockerfile: ./database.dockerfile
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./docker/.env/.env_db

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: