name: "Green = GG WP; Red = Tu peux retry!" 

on:
  push:
    branches: [ "main", "main-dev" ]
  pull_request:
    branches: [ "main", "main-dev" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: cp template env 42
      run: cp ./docker/.env/.env_42.template ./docker/.env/.env_42

    - name: cp template env nest
      run: cp ./docker/.env/.env_nest.template ./docker/.env/.env_nest

    - name: cp template env db
      run: cp ./docker/.env/.env_db.template ./docker/.env/.env_db

    - name: Launch Pong Pod
      run: make
      
    - name: show hosts
      run: cat /etc/hosts

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Test connexion au Back-End
      run: curl 127.0.0.1:8000/api/is-on

    - name: Test connexion au front-end
      run: curl 127.0.0.1:3000
      
    - name: Test connexion API
      run: curl 127.0.0.1:8080
