name: "Green = GG WP; Red = Tu peux retry!" 

on:
  push:
    branches: [ "main", "beta", "testW" ]
  pull_request:
    branches: [ "main", "beta" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Launch Pong Pod
      run: make
      
    - name: show hosts
      run: cat /etc/hosts

    - name: Sleep for 30 seconds
      run: sleep 30s
      shell: bash

    - name: Test connexion au front-end
      run: curl 127.0.0.1:3000
      
    - name: Test connexion au Back-End
      run: curl 127.0.0.1:8000
      
    - name: Test connexion API
      run: curl 127.0.0.1:8080
