name: "Green = GG WP; Red = Tu peux retry!" 

on:
  push:
    branches: [ "main", "beta" ]
  pull_request:
    branches: [ "main", "beta" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Launch Pong Pod
      run: make
