name: "Green = GG WP; Red = Tu peux retry!" 

on:
  push:
    branches: [ "main", "beta" ]
  pull_request:
    branches: [ "main", "beta" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
        
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Launch Pong Pod
      run: make
      
    - name: show hosts
      run: cat /etc/hosts
      
    - name: Test connexion au front-end
      run: curl 127.0.0.1:3000
      
    - name: Test connexion au Back-End
      run: curl 127.0.0.1:8000
      
    - name: Test connexion API
      run: curl 127.0.0.1:8080
