name: "Green = GG WP; Red = Tu peux retry!" 

on:
  push:
    branches: [ "main", "beta" ]
  pull_request:
    branches: [ "main", "beta" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Launch Pong Pod
      run: make
      
    - name: Test connexion au front-end
      run: curl localhost:3000
      
    - name: Test connexion au Back-End
      run: curl localhost:8000
      
    - name: Test connexion API
      run: curl localhost:8080
